### ISSUE TITLE
Date Countdown Improvements

### ISSUE THREAD

**Issue by swissspidy** [Bento-WordPress/gutenberg-bento#14]
As per #3, the following things can be added to make using the countdown block easier:

* Pass the current WP locale to the component
* Allow changing the number format (e.g. single digit or double digit, optionally display label)
* Maybe combine the "sub" blocks into a single block and let the user choose which unit they want to display
* Prevent using the "sub" blocks outside the countdown block (might require changes in Gutenberg)
* Make styling the "sub" blocks easier (might require changes in Gutenberg)

**Comment by luminuu** [comment]
- Change the date select label at the Date Coutdown block from "Publish" to "Date"

**Comment by swissspidy** [comment]
> Change the date select label at the Date Coutdown block from "Publish" to "Date"

Fixed in f4fdd30557e2eb383b83d6d06e2d00b8b34d250a 👍
